apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ws_brew_sim
    user: admin
    secureJsonData:
      password: password
    isDefault: true
    editable: true
